#!/bin/bash
set -e

info="$(./info)"
echo "$info"

ref="$(git describe --all --long HEAD)"

if [ -n "$TRAVIS_PULL_REQUEST" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
  exit 0
fi

build_name="linux"
if [ "$(uname)" == "Darwin" ]; then
  build_name="macosx"
elif ! sudo -v 2> /dev/null; then
  build_name="linux-docker"
fi

current_branch="$(git symbolic-ref --short -q HEAD || echo "$TRAVIS_BRANCH")"
if [ "$current_branch" != "master" ] && [ "$current_branch" != "$build_name" ]; then
  exit 0
fi

outdir="$(mktemp -d -t machineinfo-XXXXXX)"

git remote set-branches --add origin gh-pages
git fetch --all
git branch --track gh-pages origin/gh-pages
git clone --branch gh-pages $(pwd) $outdir

host="$(hostname -f)"
(
  export GIT_AUTHOR_NAME="$(git log -n 1 --format='%an')"
  export GIT_AUTHOR_EMAIL="$(git log -n 1 --format='%ae')"
  export GIT_COMMITTER_NAME="Travis CI"
  export GIT_COMMITTER_EMAIL="travis-ci@$host"

  cd $outdir
  echo "---
layout: default
---

$info" > "${build_name}/index.md"
  git add "${build_name}/index.md"
  git commit -m"System info $host build with $ref"
  git push origin gh-pages
)

if [ ! -e id_rsa.dec ]; then
  cp id_rsa id_rsa.dec
  chmod 600 id_rsa.dec
  ssh-keygen -p -f id_rsa.dec -P "$SSH_KEY_PASS" -N '' || rm id_rsa.dec
fi

git config --replace-all url.git@github.com:.pushInsteadOf git://github.com/ '^git://github\.com/$'
git config --replace-all url.git@github.com:.pushInsteadOf https://github.com/ '^https://github\.com/$'

GIT_SSH=./ssh-wrapper git push origin gh-pages

if [ "$build_name" == "linux" ]; then
  git checkout -b linux-docker-rebuild
  perl -i -e'while(<>){ if (/^branches:/) { while(<>) { last if /^\S/ } } print unless /^sudo:/ }' .travis.yml
  echo "
sudo: false
branches:
  include:
  - linux-docker
" >> .travis.yml
  git add .travis.yml
  (
    export GIT_AUTHOR_NAME="$(git log -n 1 --format='%an')"
    export GIT_AUTHOR_EMAIL="$(git log -n 1 --format='%ae')"
    export GIT_COMMITTER_NAME="Travis CI"
    export GIT_COMMITTER_EMAIL="travis-ci@$host"
    git commit -m"Build for linux-docker"
  )
  GIT_SSH=./ssh-wrapper git push -f origin linux-docker-rebuild:linux-docker
fi
