#!/bin/bash
set -e

git clone --branch gh-pages $(pwd) ~/machineinfo

host="$(hostname -f)"
ref="$(git describe --all --long HEAD)"

(
  echo "# Machine Info"
  echo "## Kernel"
  cat /proc/version | sed -e's/^/    /'
  echo "## Hostname"
  echo "$host" | sed -e's/^/    /'
  echo "# Free memory"
  free -t -m | sed -e's/^/    /'
  echo "## CPU Info"
  cat /proc/cpuinfo | sed -e's/^/    /'
  echo "## Services"
  sudo service --status-all | sed -e's/^/    /'
  echo "## Filesystem Info"
  df | sed -e's/^/    /'
) 2>&1 | tee ~/machineinfo/README.md

(
  export GIT_AUTHOR_NAME="$(git log -n 1 --format='%an')"
  export GIT_AUTHOR_EMAIL="$(git log -n 1 --format='%ae')"
  export GIT_COMMITTER_NAME="Travis CI"
  export GIT_COMMITTER_EMAIL="travis-ci@$host"

  cd ~/machineinfo
  git add README.md
  git commit -m"System info $host build with $ref"
  git push origin gh-pages
)

if [ -n "$TRAVIS_PULL_REQUEST" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
  exit 0
fi

current_branch="$(git symbolic-ref --short -q HEAD || echo "$TRAVIS_BRANCH")"
if [ "$current_branch" != "master" ]; then
  exit 0
fi

if [ ! -e id_rsa.dec ]; then
  cp id_rsa id_rsa.dec
  chmod 600 id_rsa.dec
  ssh-keygen -p -f id_rsa.dec -P "$SSH_KEY_PASS" -N '' || rm id_rsa.dec
fi

git config --replace-all url.git@github.com:.pushInsteadOf git://github.com/ '^git://github\.com/$'
git config --replace-all url.git@github.com:.pushInsteadOf https://github.com/ '^https://github\.com/$'

GIT_SSH=./ssh-wrapper git push origin gh-pages
