#!/bin/bash

build_name="$(uname | tr A-Z a-z)"
if [ "$build_name" == "linux" ] && [ "$(sudo -n -v 2>&1)" == "" ]; then
  build_name="$build_name-docker"
fi

[ "$build_name" == "linux" ] || exit

echo "Triggering rebuild of docker branch..."

rebuild_dir="$(mktemp -d machineinfo-XXXXX)"
git clone ./ "$rebuild_dir"

(
  cd "$rebuild_dir"

  git checkout -b linux-docker-rebuild
  perl -i -e'while(<>){ if (/^branches:/) { while(<>) { last if /^\S/ } } print unless /^sudo:/ }' .travis.yml
  echo "
  sudo: false
  branches:
  include:
  - linux-docker
  " >> .travis.yml
  git add .travis.yml

  export GIT_AUTHOR_NAME="$(git log -n 1 --format='%an')"
  export GIT_AUTHOR_EMAIL="$(git log -n 1 --format='%ae')"
  export GIT_COMMITTER_NAME="Travis CI"
  export GIT_COMMITTER_EMAIL="travis-ci@$(hostname -f)"
  git commit -m"Build for linux-docker"

  git push -f origin linux-docker-rebuild
)
rm -rf "$rebuild_dir"

git push -f origin linux-docker-rebuild:linux-docker
